### PR TITLE
Move Gazebo Realsense to its own repo

### PR DESCRIPTION
**Pull request by anselmolsm**

### CODE REVIEW

**Comment by rchiossi** [comment]
yeah, I agree with @mbelluzzo . There is no code dependency, so we don't need it as a submodule.

**Comment by anselmolsm** [comment]
Second commit (submodule) discarded.

**Comment by rchiossi** [comment]
The readme needs an update to point to it. Also, it might be good to update the GZSitl reference to contain the repo address.

**Comment by mbelluzzo** [comment]
Merged with proposed fixes

**Comment by anselmolsm** [comment]
Cool, tks

**Pull request closed without merging**
