### PR TITLE
Get rid "gcs" terminology + mv tests to the correct folder.

### PR DESCRIPTION
**Pull request by mbelluzzo**

### CODE REVIEW

**Comment by mbelluzzo** [comment]
Testbed commit -> I just did that to remove coav_gcs without break it while we dont have coav-sim merged because we will have ppl looking at the project in between. So is temporary but not pointless. So I'm going to merge the commits except the Move test that needs to be re-done.

**Comment by rchiossi** [comment]
Yeah, i figured as much. That's fine, there is no harm in merging it.

**Comment by mbelluzzo** [comment]
>  polarhist_test.cc should be renamed to polarhist_sample.cc and keept at the samples folder. It is more of a sample on how to use polarhist than a polar hist test itself.

In this case you are totally write, its a small app that shows the usage of a given detector and has a simple output used for demonstration.

> Commit "Move test apps out of 'samples' folder" is all wrong. test.cc should be renamed to  vdebug and moved into the tools directory.
> The idea is to keep tests that can be automated in tests/ folder, and thats not the case with polarhist_test.

But here is where I have to disagree, test.cc is a horrible sample, it actually has little to no value as a sample at all. It really isn't an automated test but its a testing tool more than a sample. Its only purpose is to help one "test" if the simulated camera input is working. Maybe it should be coav-control's neighbor under tools?

**Comment by rchiossi** [comment]
well, that's what I wrote there... "test.cc should be renamed to vdebug and moved into the tools directory"

**Comment by mbelluzzo** [comment]
I'm getting old fast :-(

**Pull request closed without merging**
